providers:
  ethereum: "0x2f39D218133AFaB8F2B819B1066c7E434Ad94E9e"
  polygon: "0xd05e3E715d945B59290df0ae8eF85c1BdB684744"
  arbitrum: "0xa97684ead0E402dC232d5A977953DF7ECBaB3CDb"
  optimism: "0x5343b5a6ec9d8b9b1b66b62a09a57f3bafca1c05"
  base: "0x252B36B38B47aFe6B06FfA34a7C37DbffCC9B8F4"